baseURL = "https://aliquote.org/"
languageCode = "en"
title = "aliquote.org"
theme = "aliquote"
pagination.pagerSize = 10
enableRobotsTXT = true

# disable
pygmentsUseClasses = true
pygmentsStyle = "bw"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[blackfriday]
fractions = false

[markup.goldmark.renderer]
unsafe = true

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

[author]
name = "chl"

[params]
mainSections = ["tweet"]
featherIconsCDN = true
wc = true
mode = "auto"

[outputs]
home = ["HTML", "RSS", "JSON"]

[[params.social]]
name = "articles"
icon = "list"
url = "/post"

[[params.social]]
name = "archives"
icon = "archive"
url = "/writings"

[[params.social]]
name = "about"
icon = "info"
url = "/about"

[[params.social]]
name = "/"
icon = "search"
url = "/search"

[taxonomies]
tag = "tags"
category = "categories"
